### ISSUE TITLE
FxA-57: verification reminder

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#1]

**Comment by rfk** [comment]
Latest: need to confirm whether operational changes to auth-mailer landed in train-66

**Comment by rfk** [comment]
@ryanfeeley if you have a dashboard you're looking at for these metrics please link it here.

We'll ship this after the node4 upgrade.

**Comment by davismtl** [comment]
Here is the graph Ryan was referring to in product meeting that is shows about 61% for verification. https://sql.telemetry.mozilla.org/queries/867#1485

**Comment by ryanfeeley** [comment]
I think increasing the verification rate is worthy of its own OKR.

**Comment by rfk** [comment]
The verification rate is subsumed by the more general "success rate of connecting to sync", since having a verified account is a prerequisite for this.  We could certainly call it out as a KR though.

**Comment by davismtl** [comment]
Code landed but need to configure it server side. Sync up with jrjm and jbuck

**Comment by rfk** [comment]
This remains blocked by the node4 upgrade

**Comment by davismtl** [comment]
Should go out on the next train (69). @rfk will reach out to jon to see what the status is.

**Comment by davismtl** [comment]
from mtg
@vladikoff will check with jrjm to see what remains and that everything will be launched in the right order.

**Comment by davismtl** [comment]
from mtg: 
still blocked by node 4

**Comment by davismtl** [comment]
going out with train 72, will enable for 10%.

**Comment by davismtl** [comment]
from mtg: 
- need to tell jrgm and jbuck to flip the switch on 10%
- need to check the urls in email reminders to make sure we'll be measuring properly

**Comment by davismtl** [comment]
from mtg:
- moved to train 73

**Comment by davismtl** [comment]
from mtg: 
- shipped at 10% in train 73
- ready to start measuring

**Comment by davismtl** [comment]
@vladikoff please add the links to the dashboards we plan to monitor to measure success. 

Thanks

**Comment by rfk** [comment]
We had to disable this in production due to unexpected operational effects on the database :-(

I'm going to put it back in "shipping", and @jrgm is going to try an experiment to see if we can resolve them.  @vladikoff @jrgm please link to a tracking bug for this work if we have one.

**Comment by davismtl** [comment]
from mtg:
we need to investigate it more because we had problems in dev environment too.  Causing db to run out of active connection.

**Comment by davismtl** [comment]
from mtg:
- we're re-doing some of the queries (refactoring code)
- will move back into building

**Comment by vladikoff** [comment]
Building discussion: https://github.com/mozilla/fxa-auth-db-mysql/issues/196

**Comment by davismtl** [comment]
from mtg:
- started investigating the issue we had yesterday (database related)
- will be working on this for next 2 weeks

**Comment by rfk** [comment]
from mtg: @vladikoff and @jrgm are going to try out a new locking mechanism in MySQL later today

**Comment by davismtl** [comment]
from mtg:
- in train 81 behind a flag with a rate

**Comment by davismtl** [comment]
from mtg:
- we think it's shipping next week (cutting this week)
- @rfk will check if it will be pref'd to "on"

**Comment by rfk** [comment]
> @rfk will check if it will be pref'd to "on"

It will not; pref on in train-82

**Comment by davismtl** [comment]
from mtg: 
- no updates. still aiming for 82
- feature still looks stable

**Comment by davismtl** [comment]
from mtg:
- going out this week
- will measure in Kibana
- should see rate of verification to creation improve in redash

**Comment by davismtl** [comment]
from mtg:
- briefly went out this week and then rolled back
- mysql is acting "strange", as in data replication stops working which means we have no backups.
- jrgm to test on just one server
- @jbuck proposes to review this during work week.

**Comment by davismtl** [comment]
from mtg:
- will dig into this during the work week next week

**Comment by vladikoff** [comment]
from mtg: @jrgm to disable replication for the `verificationReminders` table

**Comment by davismtl** [comment]
from mtg:
- @jrgm is trying it out on stage this week, according to vlad and rfk

**Comment by davismtl** [comment]
from mtg:
- this was forgotten over the last 2 weeks. Ryan will follow up with him.

**Comment by rfk** [comment]
status via IRC:
"I've done it on latest. It's relatively quick to do. Just custom parameter list, set read_only = 0, and alter table verificationReminders engine=blackhole. Then wait long enough to know that replication isn't going to break on some edge case."
