### ISSUE TITLE
FxA-86: strengthen passwords v1

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#10]

**Comment by rfk** [comment]
From aha: https://mozilla.aha.io/features/FXA-86

**Comment by davismtl** [comment]
From Aha: 
"
As a user, I want Firefox to help me choose a strong password so I feel confident that my account is safe.

DOD: User has confirmation and confidence that the password they've created is strong by Mozilla standards

Possible A.C.
Visual warning indicator of a user's password strength: Weak > Strong
 User sees reminder to not reuse a password
 User sees tool to help them generate/improve their password.
 Possible: automated rejection of  known bad passwords (i.e. "password")
 Possible: Users syncing critical data (like password keychain) may see stronger reminders of password strength needed

"

**Comment by vladikoff** [comment]
from mtg:
- measure what we deployed now with the new prompts. 
- might be affective sign up success?
- Many like the Visual indicator
- Do an experiment, see which has the lowest # of hits.

**Comment by davismtl** [comment]
we're getting pretty good at this
