### ISSUE TITLE
Send an email to help users who do not connect another device on signup/signup.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-features#114]
A relatively low % of users connect a 2nd device within 48 hours of a signup. We attempt to help users connect a 2nd device at the end of the signup and signin flows, but if users fail to add a 2nd device at that point, they most likely won't do so.

After 24, 48, or 72 hours, we could do something similar to "verification reminders" and email users who have not connected a 2nd device. "Hey, we see you haven't connected a 2nd device. Did you know you could make your life better with X if you did so?"

**Comment by rfk** [comment]
The basket/marketing folks are currently running an experiment with something similar; if they see good results, we could consider folding it into our infrastructure to support a tighter integration.  @davismtl do you have that link handy to the experiment description from marketing?

One suggestion along similar lines that @seanmonstar had, was that there are some circumstances where we *know* the user intended to set up a second device.  For example, they sent themselves an SMS, or they clicked through to the app store.  If they take one of those actions but fail to connect the second device, that's a very strong signal we may be able to reach out to them to help them out.

**Comment by davismtl** [comment]
Correct, marketing is already working on this.
https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=65345536

They have tested the 24h reminder and are now testing the 7 day reminder for those that never opened the 24h reminder.

Currently, I have no need to integrate it directly into our infrastructure. I can however see benefits for lifecycle marketing team to have the emails on their end to avoid sending 2 emails to a user in short period of time. Also, to my knowledge, they have full deliverability right now that is another benefit to having them send it out.
