### ISSUE TITLE
Send a push notification to all devices on profile change

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-features#118]
If a user has multiple connected devices and changes their profile info on one device, there is significant lag before that info is updated on the other devices. This lag time could be greatly reduced by sending a push notification to all devices.

Ref https://github.com/mozilla/fxa-content-server/issues/4755

**Comment by rfk** [comment]
Just some high-level notes here while I think of them...

* The auth-server holds the device registration records and has the ability to send push notification sto devices
* The profile-server is the thing responsible for updating profile information and is a separate system

So to make this push message we could either:

* Have the profile-server server send the message to the auth-server, which forwards it to connected devices; or
* Have the front-end code upload its changes to profile-server, and then separately trigger the notification by calling the /devices/notify endpoint on the auth-server

The first would be slightly more reliable, at the cost of tighter coupling, as I don't think the profile-server currently knows anything about the auth-server.

**Comment by eoger** [comment]
I'd be happy to work on this once we decide on which solution we would like to go with. (I'm leaning a bit towards the first solution, which feels a bit less hacky too me).

**Comment by rfk** [comment]
> (I'm leaning a bit towards the first solution, which feels a bit less hacky too me).

Sounds fine to me.  The profile-server can't directly call the /devices/notify endpoint, since it doesn't hold a sessionToken.  We could instead have it write events into an SQS queue, and have the auth-server pull them off and send them out to the devices.

**Comment by vladikoff** [comment]
@eoger can this be closed?

**Comment by eoger** [comment]
Kill it 🔫
