### ISSUE TITLE
Review new ESP

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#119]
We would like to explore new ESPs that might have better expertise around mail deliverability.

This is related to our poor deliverability with Outlook and is a take-away around our discussions related to using marketing's SF for email. (see: https://waffle.io/mozilla/fxa-features/cards/58af5e5d6166e10302399bb1)

**Comment by rfk** [comment]
@jrgm for planning purposes, are there things we could be looking into on the application side to support alternate senders such as socketlabs, or would it mostly be in configuration changes to postfix in deployment?

**Comment by davismtl** [comment]
We are now able to support two ESP at the same time
