### ISSUE TITLE
FxA-104: remove account lockout

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#12]
Engineering bug tree: https://waffle.io/mozilla/fxa?milestone=FxA-104:%20remove%20account%20lockout

**Comment by shane-tomlinson** [comment]
The task for this feature is to kill it with fire.

See:
https://github.com/mozilla/fxa-content-server/issues/3949
https://github.com/mozilla/fxa-auth-server/issues/1359
https://github.com/mozilla/fxa-auth-mailer/issues/186
https://github.com/mozilla/fxa-js-client/issues/208
https://github.com/mozilla/fxa-auth-db-mysql/issues/146
https://github.com/mozilla/fxa-customs-server/issues/120

And the PRs:

https://github.com/mozilla/fxa-content-server/issues/3956
https://github.com/mozilla/fxa-auth-server/issues/1360
https://github.com/mozilla/fxa-auth-mailer/issues/187
https://github.com/mozilla/fxa-js-client/issues/209
https://github.com/mozilla/fxa-auth-db-mysql/issues/147

**Comment by vladikoff** [comment]
from mtg:

Done in train-67
