### ISSUE TITLE
OAuth Support for Web Extensions

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-features#121]
Feature doc: mozilla/fxa#249

**Comment by davismtl** [comment]
from mtg:
- Need to add a feature doc for great web extension feature and the various phases (e.g. hover pad)
- Ask Pageshot/ screenshot if they want to encrypt their data

**Comment by davismtl** [comment]
from mtg:
- we had team meeting to decide about next steps. We have opted to make a prototype.
- @vladikoff is working on the prototype. 2/3 of it is done. (most complicated parts)
- once prototype is done, we'll consider is defined

Next steps:
- @vladikoff to wrap up feature doc and add to this card

**Comment by davismtl** [comment]
from mtg:
- should have feature card by next product meeting

**Comment by vladikoff** [comment]
Feature doc: https://github.com/mozilla/fxa/pull/249

**Comment by davismtl** [comment]
from mtg: 
- vlad created doc above
- feeley made a new design for hoverpad which will be integrated next week 
- deployed box for hoverpad devs to test login and sync
- julie and alex will join hoverpad meetings
- we will review the request for sf work week with screenshots. Let's just make sure they have everything they need to start working before hand. we want to make them autonomous.

**Comment by davismtl** [comment]
FEATURE CARD MOVED TO NEW PRODUCT BOARD. ADD NEW COMMENTS HERE: 
https://projects.growthhackers.com/s2/xXSQaef9nvV8CZ86sCHbcg
