### ISSUE TITLE
DevOps Q2

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-features#122]
This is the related to the OKR about reducing dev ops backlog.

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa/issues/238

**Comment by vladikoff** [comment]
DevOps Backlog is here: https://waffle.io/mozilla/fxa?milestone=FxA-122:%20DevOps%20Q2

**Comment by davismtl** [comment]
from mtg:
- no updates to give here

**Comment by davismtl** [comment]
from mtg:
- okr on track
- 28% of bugs fixed. 2% to go! \o/

**Comment by davismtl** [comment]
FEATURE CARD MOVED TO NEW PRODUCT BOARD. ADD NEW COMMENTS HERE: 
https://projects.growthhackers.com/s2/vYEQhAiVFTBJtJuPEqEV9w
