### ISSUE TITLE
Device manager quality

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#123]
A tracking milestone for our backlog of device-manager quality issues.  Engineering bug backlog:

  https://waffle.io/mozilla/fxa?milestone=FxA-123:%20Device%20manager%20quality

**Comment by rfk** [comment]
@ryanfeeley @davismtl given the flurry of device-manager-related bugs coming in, I'm creating this "feature" to track them all.  Let's discuss in product meeting how to prioritize these relative to other work going on.

**Comment by davismtl** [comment]
from mtg:
- clean up old sessions to remove empty sessions from list
- emoji's and unicode characters are causing problems. We're doing early tests in dev environment to see if we can fix this.

**Comment by rfk** [comment]
> emoji's and unicode characters are causing problems.

To be clear: we've confident we know why this is happening, it's due to unicode encoding issues in the database.  It'll require a non-trivial db migration to fix, but we know what we have to do, we just need to prioritize it.  @davismtl is this worth explicitly prioritizing for the next dev cycle?

**Comment by ryanfeeley** [comment]
@rfk Emojis are perhaps not a big deal, but will this problem be more obvious in other locales? For example, would other languages see this problem with default Firefox names?

**Comment by davismtl** [comment]
I think @ryanfeeley asks a great question. Do we think it happens for other characters than just emojis. For example, the Beta symbol for Firefox Beta on iOS also breaks.

If we think it may be breaking for a wider range of characters, then it may be worth doing next sprint. If not, it can probably wait a bit.

**Comment by rfk** [comment]
I've seen both the beta symbol and Chinese characters displayed as "?", so yes, probably broader than just emojis.

**Comment by davismtl** [comment]
> is this worth explicitly prioritizing for the next dev cycle?

I just tried it with non-latin characters and it always breaks so I think this should be pretty high priority.

Note that sync team is also now linking to device manager from synced tabs side bar so more people will notice.

**Comment by rfk** [comment]
From our discussion today, we decided to:

* Split off the web-session-related issues into their own tracking milestone, for independent prioritization
* Discuss trying to resolve the unicode/emoji issue in the coming dev cycle

**Comment by rfk** [comment]
From mtg: let's triage most of these back into general quality bugs rather than a separate milestone
