### ISSUE TITLE
Change Primary Email (Phase 2)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#125]
This is the follow up to #27

Add feature doc here:
https://docs.google.com/a/mozilla.com/document/d/1SaJEOGi2GEd69-Rype480Syl7DPdCSFSfRxmS7oKUrE/edit?usp=sharing

**Comment by davismtl** [comment]
from mtg:
- move content from phase 1 feature doc into a phase 2 document
- review that the 4 phases still make sense.

**Comment by vbudhram** [comment]
Started feature doc https://docs.google.com/a/mozilla.com/document/d/1SaJEOGi2GEd69-Rype480Syl7DPdCSFSfRxmS7oKUrE/edit?usp=sharing

**Comment by davismtl** [comment]
from mtg:
- @davismtl need to help with first sections and featrue doc
- @ryanfeeley needs to help with design section of document

**Comment by davismtl** [comment]
from mtg: 
- ryan and alex to get together next week to work on the above doc

**Comment by davismtl** [comment]
FEATURE CARD MOVED TO NEW PRODUCT BOARD. ADD NEW COMMENTS HERE: 
https://projects.growthhackers.com/s2/i6w2LrU971kJOEXUajRC_Q
