### ISSUE TITLE
fix email-on-acid

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#128]
We have a Q2 OKR of achieving 100% deliverability in email-on-acid, so let's make a feature to track all the little things we're planning to try in that regard.

**Comment by davismtl** [comment]
from mtg: 
- was looking good for outlook
- apparently we use bad link tags so we need to investigate

**Comment by seanmonstar** [comment]
The link tags are from us adding in the [View Actions](https://developers.google.com/gmail/markup/reference/go-to-action#view_action) for Gmail. I can't find anything that says that it is actually harmful to any client, as they generally just strip tags they don't know.

**Comment by davismtl** [comment]
@rfk 
What distinctions did we want to make between the efforts on this card and this one:
https://waffle.io/mozilla/fxa-features/cards/584075ded8a02a0e005339b0

I'm realizing this is not very clear. It'll make migrating this card a bit easier.

**Comment by rfk** [comment]
I filed this to represent the "next round" of email deliverability work, specifically following up on any suggestions from e-on-e linter and other checks (like the ones you posted recently about image domains) to try to get our score up to 100%.  I'm very open to a better title for this work :-)

**Comment by rfk** [comment]
This is no longer a useful milestone, closing out the feature card
