### ISSUE TITLE
FxA-41: signin funnel metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#13]
https://docs.google.com/document/d/1et1zy1f4qimYqpm6a3YGNinvLbFoRjOX8OqooPGg3O8/edit#

**Comment by rfk** [comment]
I've started drafting my thoughts on this feature at the above-linked google doc.

**Comment by rfk** [comment]
@davismtl this is ready for a detailed review from you

**Comment by davismtl** [comment]
This looks good. I left a few additional comments for @philbooth @rfk . There were two things that I commented on:
- Our ability to segment by **device type**, **OS**, **Country** or **Firefox version** which will be essential to understanding our funnels. There was no mention of this in the document.
- Most chart examples were absolute numbers. We need to also plot our charts with % rather than just looking at absolute numbers. The two combined give the big picture. Those individual rates are what we will optimize over time to get the highest funnel completion rate.

**Comment by rfk** [comment]
This is ready for a final r? from @davismtl

**Comment by davismtl** [comment]
r+
@philbooth did a great job at adding definitions everywhere and allowing us to see and understand how we will be able to use the data to understand user flow and to make decisions.

Any further recommendations or changes will likely only surface once we've all played with this data and uncover new questions we cannot answer.

**Comment by davismtl** [comment]
from mtg: 
-Charts/queries are a WIP

rfk is already getting value out of the data that landed.

**Comment by davismtl** [comment]
from mtg: 
phil and alex met this morning to double user funnels and match them up with all the flow event. We flagged a few missing metas and events. Nothing too serious.

**Comment by davismtl** [comment]
A lot of issues open. Vijay is helping out.
Making sure that in Train 72, we have enough in place to measure sign in success rate for next sprint.

**Comment by davismtl** [comment]
from mtg:
- to re-write spreadsheet with various user funnels and map events to each step. may provide clarity for queries (alex's might not be good as a result)
- missing full days of data
- noticing funny timestamps

**Comment by davismtl** [comment]
from mtg: 
- Meeting next week with @philbooth and @rfk to review and discuss remaining work and challenges
- Security scans are causing anomalies in our data

**Comment by davismtl** [comment]
from mtg:
- in 74, we are fixing some validation that prevented import. should improve quality of data

wip: https://sql.telemetry.mozilla.org/queries/1674/source#2973

**Comment by rfk** [comment]
We can bump a lot of quality/enhancements bugs out of this milestone, I think it's pretty close to "shipping".  We need to get all the important graphs together into a single dashboard, so that we're confident we have all the pieces we need.

**Comment by davismtl** [comment]
from mtg:
- will continue to use for another week but should probably be closed if no problems are detected.
- beyond the net week, we should just create new feature cards and issues for enhancements

**Comment by davismtl** [comment]
closing this. looks good
