### ISSUE TITLE
Amplitude Integration

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#134]
This could probably use a feature-doc, but in the meantime here's some useful context:

* We want to send these events to amplitude: https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/

* We'll need to export them via their HTTP API: https://amplitude.zendesk.com/hc/en-us/articles/204771828-HTTP-API

* And the data flow will probably end up looking like this: https://www.lucidchart.com/documents/edit/a031bec6-a927-4420-850a-96c50307c993

**Comment by davismtl** [comment]
Done. Closing
