### ISSUE TITLE
FxA-110: content-server dependency audit

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#15]

**Comment by vladikoff** [comment]
from mtg:
- not sure what this feature is about. (vs #17)

**Comment by rfk** [comment]
@shane-tomlinson described this to me as "there are dependencies we're using in content-server that we probably don't need to be using at all, and we could stop using them to decrease the download size".

**Comment by rfk** [comment]
@shane-tomlinson is this feature still useful, or have we tackled the low-hanging fruit here already?

**Comment by shane-tomlinson** [comment]
@rfk - AFAICT, we haven't done anything, so no, we haven't eaten any low-hanging fruit.
