### ISSUE TITLE
FxA-108: update all the deps

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#17]

**Comment by rfk** [comment]
Blocked on node4 upgrade

**Comment by vladikoff** [comment]
Feature doc: https://github.com/mozilla/fxa/tree/master/features/FxA-108-update-deps

**Comment by davismtl** [comment]
from mtg
On track for end of Q3. We recently merged a lot of stuff. Blocked by node 4 being released everywhere.

**Comment by davismtl** [comment]
from mtg:
-blocked by node 4 upgrade
- security reporter is live
- need to review which repos to add to security monitoring

80-90% done

**Comment by davismtl** [comment]
from meeting:
- only OAuth server needs updating

**Comment by vladikoff** [comment]
- [X] OAuth server was updated.
