### ISSUE TITLE
FxA-85: sync data choices refresh

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#18]
From [AHA](https://mozilla.aha.io/features/FXA-85)

As a new user to FxA/Sync, I want to see and configure my data sync options so I get the Firefox I want on all my devices and know I'm in control of my data.

DOD: When a user signs up, they clearly  understand and can edit which browser data is being synced as

Possible A.C.
-     User sees registration and/or first-run flows specifying sync data options
-     User can toggle on/off data options
-     User sees link to learn more about data sync options and Fx Sync
-     Sync Passwords is off by default

**Comment by davismtl** [comment]
Look for old Aha card and add it here.

**Comment by rfk** [comment]
Here it is: https://mozilla.aha.io/features/FXA-85

**Comment by ryanfeeley** [comment]
@rfk @davismtl We built and shipped the components of this that made sense. We decided against disabling password syncing as it’s a commonly used feature. We don't link to SUMO to learn more as it's a detour in registration process. I think we can close this.

**Comment by davismtl** [comment]
@rfk 
Do we consider this shipped? Were there any success metrics defined that should be looked at?

**Comment by ryanfeeley** [comment]
@davismtl Great question! Probably worth tossing into the Measuring column. The original documentation for the feature is here: https://github.com/mozilla/fxa/tree/master/features/shipped/FxA-33-choose-what-to-sync
The feature was created for a few reasons:
1. It was a more natual place to ask the user after submitting the registration form than after verifying
2. We used to ask after verifying in native browser UI (dialog) which felt clunky and interrupted the flow of any onboarding experience
3. We knew that a large % of users were opting out of syncing something, so it made sense to maket a mandatory part of the flow
4. We knew that many users didn't know what they were signing up for and thought this would help, ideally driving multi-device engagement (not trackable at the time).

**Comment by rfk** [comment]
-> measuring; let's review the feature doc and metrics in next product meeting, or sooner if you want to do it asynchronously

**Comment by rfk** [comment]
@rfk to review this and link to the appropriate metrics, if we haven't already

**Comment by rfk** [comment]
@ryanfeeley please link to datadog dashboards here

**Comment by rfk** [comment]
People are defnitely using it :-);  we have one open question about what to do about success rate for users who do not submit this form

**Comment by ryanfeeley** [comment]
Submissions of the Choose What To Sync screen and unchecked items, stacked. Around half of user uncheck something, with History being the most unchecked item. https://app.datadoghq.com/graph/embed?token=a39a04a508d59ff0bf6ecafab2917b28b9ad2971c34b975db388e9be650da01f&height=500&width=1000&legend=true

**Comment by rfk** [comment]
> we have one open question about what to do about success rate for users who do not submit this form

I think we can safely deal with this as part of our ongoing work to measure and improve the signup/signin success funnel.  The rest of it, I consider complete.
