### ISSUE TITLE
FxA-70: KPI dashboards

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#2]
Engineering bug tree: https://waffle.io/mozilla/fxa?milestone=FxA-70:%20KPI%20dashboards

Dashboard: https://sql.telemetry.mozilla.org/dashboard/fxa-kpis

**Comment by davismtl** [comment]
@rfk  Have we defined what KPIs we want displayed in this dashboard?

**Comment by rfk** [comment]
The current definitions are in https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards although I think we've evolved them slightly since then.  Some we have and just need to make sure we're linking to, some we should be able to generate soon since the metrics events are now in production.

**Comment by rfk** [comment]
Next step is getting the metrics export pipeline running, so moving this into "shipping"

**Comment by davismtl** [comment]
@rfk do we want to make the KPI dashboards a different issue from the pipeline?

**Comment by rfk** [comment]
> do we want to make the KPI dashboards a different issue from the pipeline?

I don't understand what this would mean in practice - are you suggesting separate feature cards for "build KPI metrics pipline" and "build KPI metrics graphs"?

I think we'll certainly have some follow-up features of the form "build graph of XYZ" as we evolve our KPIs, but I think it's OK to keep the original graphs defined in [1] as part of this feature, to have something concrete for the pipeline to work towards.

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards

**Comment by davismtl** [comment]
Ok that makes sense

**Comment by davismtl** [comment]
Waiting for some our current metrics to be exported in a new format. Phil is managing this right now. Might be ready as of train 67. rfk will double check.

**Comment by vladikoff** [comment]
cc @vladikoff @rfk

**Comment by rfk** [comment]
The final piece of data should be available in re:dash this week \o/

**Comment by vladikoff** [comment]
per yesterday meeting I moved this to `measuring`. Let me know if that is the right place for that @rfk @philbooth

**Comment by davismtl** [comment]
Data landed in s3 and is being moved over to re:dash. Next steps is to make the dashboards.

**Comment by davismtl** [comment]
from mtg
Phil has been making a lot of the queries/charts. We will make dashboards once they are finalized. Should have a demo on Monday.

**Comment by davismtl** [comment]
Dashboard: https://sql.telemetry.mozilla.org/dashboard/fxa-kpis
Needs to back-fill with more data. Will go into review soon.

**Comment by davismtl** [comment]
Ran out of disk storage when we tried to backfill. Resize of disk froze. Will double check later today the status of this.

**Comment by davismtl** [comment]
Should be done with this next week. :D

**Comment by davismtl** [comment]
from mtg:
Should be done with this next week. :D (he means it this time)

**Comment by davismtl** [comment]
from mtg:
- may need to re-import data again (or change table)
- working on segmentation and figured historical data importer

**Comment by davismtl** [comment]
from mtg:
- very close to done
- just need to make the last couple of graphs. Data looks good.

Also meeting next week with @philbooth and @rfk to review.

**Comment by davismtl** [comment]
from mtg:
- small fix landed for oauth reliers
- want to add time to auth

Go play with it: 
https://sql.telemetry.mozilla.org/dashboard/fxa-kpis

**Comment by rfk** [comment]
We closed out all the issues in this milestone.  Next step is for @davismtl to review the dashboard and see if everything looks as it should, so I'm moving this to 'measuring'.

**Comment by davismtl** [comment]
Closing \o/
