### ISSUE TITLE
FxA-15: connected apps in the settings view

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#20]
Engineering work is here: https://waffle.io/mozilla/fxa?milestone=FxA-15:%20connected%20apps

**Comment by vladikoff** [comment]
Feature doc https://github.com/mozilla/fxa/issues/171

**Comment by davismtl** [comment]
Based on discussions, we seem to be headed towards releasing device management first and then adding oauth "services"  or "apps" after to the same view for simplified management. @rfeeley seems to have a UI in mind.

**Comment by vladikoff** [comment]
from mtg: 
- new mock up available
- feature doc in the works, needs to include feature flags that hide the list.

**Comment by rfk** [comment]
proposal needs feedback from @davismtl and @ryanfeeley

**Comment by davismtl** [comment]
Sorry for delay, just to clarify. Do you need my feedback on producing new mockups and on the feature doc?

Thanks for clarifying

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/4213

**Comment by davismtl** [comment]
from mtg:
@ryanfeeley and alex to review services section
feeley also working on icons for devices and services

Phase 1 activating on october 3rd without apps.

**Comment by davismtl** [comment]
from mtg:
@ryanfeeley and alex to review services section
feeley also working on icons for devices and services

Phase 1 activating on october 3rd without apps.

**Comment by davismtl** [comment]
from mtg:
- need a generic icon for services
- display a confirmation message after disconnection. @ryanfeeley says he likes what I wrote but we should add a message that says to also go and logout of that service.
- postponing adding a small text above device / service view to tell users what to expect when they click disconnect on a service until we give oauth access to more data (e.g. sync)

**Comment by davismtl** [comment]
from mtg:
- vlad to sync up with feeley (away on PTO)

**Comment by davismtl** [comment]
from mtg:
- new default icon for apps. First letter of services in a circle
- @vladikoff any other update to add here?

**Comment by vladikoff** [comment]
Feedback addresses. now measuring ...

**Comment by davismtl** [comment]
from mtg:
- in train 74 for 100% of users

**Comment by rfk** [comment]
It's shipped!  We can see usage data in datadog, and there's a small number of OAuth app disconnects.

@ryanfeeley is noticing UX fixes in realtime in this meeting :-)

**Comment by rfk** [comment]
@vladikoff will review the numbers in datadag and see if we can close this out

**Comment by davismtl** [comment]
from mtg:
@vladikoff looked at numbers but needs to summarize results in feature document.
