### ISSUE TITLE
FxA-79: mailcheck pt2

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#28]
New proposed design with a red tool tip to tell users that their email is invalid. Will be checking a list of misspelled email records.

**Comment by vladikoff** [comment]
from mtg: 
- new design for mailcheck:
  - red
  - below the field
  - make it more like the spell check feature
- ship with improvements to everybody and measure the changes.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/3430

**Comment by vladikoff** [comment]
> from mtg:
new design for mailcheck:
red
below the field
make it more like the spell check feature
ship with improvements to everybody and measure the changes.

@divyabiyani is working on this 👍

**Comment by davismtl** [comment]
from mtg:
- for train 82, in development

**Comment by davismtl** [comment]
from mtg: 
- ready but not deployed. still on track for 82

**Comment by davismtl** [comment]
from mtg:
- no update. still on track for 82

**Comment by davismtl** [comment]
from mtg:
- it's live! \o/
- we should see less email bounces
- @ryanfeeley checking on metrics

**Comment by davismtl** [comment]
from feeley during mtg:
- less bounces during registration
- will continue investigation

**Comment by davismtl** [comment]
from mtg:
- we need to look at bounce rates after 82
- see if there was also a drop in 83 (blacklist)
- @vladikoff @ryanfeeley to log results here.

**Comment by davismtl** [comment]
from mtg:
- @ryanfeeley still to check for impact of release on train 82

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/25723775/70c98ec2-30e7-11e7-903e-33cb28b5c73b.png)

We saw a slight decrease in handleBounce errors in this train-82

**Comment by vladikoff** [comment]
We saw a slight (modest) decrease in handleBounce errors in this train-82.
