### ISSUE TITLE
FxA-83: signin confirmation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#3]
Engineering bug tree: https://waffle.io/mozilla/fxa?milestone=FxA-83:%20signin%20confirmation

**Comment by davismtl** [comment]
I added myself as assignee because mozilla/fxa-auth-mailer#185 talks about creating a feature document for being notified about clicks on "if this wasn't you" in security emails.

This issue seems to already be active though. I'm just flagging it so that we review/discuss if the feature document is required at this stage and if so where it lies within our designing priorities.

**Comment by rfk** [comment]
@davismtl I was chatting about that issue with @shane-tomlinson last night, and I think we can profitably split it into two things:
- A first, quick version that doesn't have any new UI, but just logs some metrics events when taking the user to the existing change/reset password page.
- A second, more elaborate version where we solicit input from the user about exactly what trigger their concern, and log more detailed metrics.

The first of those we could land as part of sign-in confirmation feature, while the second seems big enough to spin out into a stand-alone feature.  What do you think?

**Comment by rfk** [comment]
In other words, make a feature out of https://github.com/mozilla/fxa-auth-mailer/issues/185#issuecomment-234010096 while doing a basic no-frills version of it with https://github.com/mozilla/fxa-auth-mailer/issues/185#issuecomment-234373886

**Comment by rfk** [comment]
Latest update: train-66 has this disabled on iOS, train-67 will include more logging in auth-server to confirm success /error rate, and email links will include utm_\* parameters.  We need to confirm how we'll injest the utm_\* parameters.

**Comment by rfk** [comment]
@vbudhram please create the necessary graphs from the new metrics that we shipped in train-67.

**Comment by vladikoff** [comment]
from mtg: to close this we  need to get stats and metrics from train-68

**Comment by vbudhram** [comment]
Dashboards for this feature:
https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/FxA%20Sign-in%20Confirmation

https://app.datadoghq.com/dash/172590/fxa-content---emails?live=true&page=0&is_auto=false&from_ts=1470778945737&to_ts=1473370945737&tile_size=m

https://app.datadoghq.com/dash/163668/fxa-content---signin-confirmation

**Comment by davismtl** [comment]
In Kibana, we are measuring about 92% completion rate. (confirm/start)
In Datadog, front-end data is putting the number in the 83-84% completion rate.

Since the discrepancy is pretty big, @vbudhram will double check in re-dash with the new flow events.

**Comment by rfk** [comment]
I've done a first cut at looking at this via flow metrics in re:dash

  https://sql.telemetry.mozilla.org/queries/1197/source

Unfortunately it seems to correlate closely with the datadog front-end data, at around 84% completion rate:

  https://sql.telemetry.mozilla.org/queries/1197/source#2093

But we should probably get a second set of eyes on it.  What I've done is:
1. Find all flow_ids that have an `account.login` event, and `service=sync`.
2. For all those flow_ids, find the ones that also have an `account.confirmed` event.
3. Count each group and show the ration of the later to the former on a daily basis.

IIUC, any login flow that matches (1) should generate a sign-in confirmation email, except for iOS.  I'll see if I can exclude iOS from the metrics.

**Comment by rfk** [comment]
>  I'll see if I can exclude iOS from the metrics.

It doesn't seem to have made much of a difference.  Hmmm.  I don't have any immediate theories for why the Kibana dashboards are the odd one out here.  @vbudhram thoughts?

**Comment by rfk** [comment]
As an additional check, the ration of flows with an `account.login` to flows with an `account.signed` is consistent with this number, at about 83%:

  https://sql.telemetry.mozilla.org/queries/1199/source#2097

**Comment by rfk** [comment]
Here they are broken down by context:

  https://sql.telemetry.mozilla.org/queries/1200/source#2099

Interestingly, the completion rate is significantly lower in the `iframe` and `fx_firstun_v2` contexts than it is in, say, the desktop contexts.

**Comment by rfk** [comment]
One possible source of discrepency is that our stashed flow event data only lasts in memcache for 30 minutes.  If the user takes more than 30 minutes to receive the email and confirm the login, they'll show up in the kibana dashboard metrics, but not the flow metrics.

**Comment by vbudhram** [comment]
@rfk Looked into this a little and noticed that the difference between login counts is about 1% and the difference between confirmed counts is about 10% higher on any given day for flow metrics and kibana.

For confirm events, they are logged at exactly the same spot, https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L1317. Your idea about memcache seems plausible, is it possible to get the number of items that are expiring?

**Comment by davismtl** [comment]
from mtg
@vbudhram and @rfk to do the following:
- In order to see if 10% users are taking more than 30 minutes, we will try to analyze completion times in kibana.
- We can also see if the bell curve in Re:Dash cuts off at 30 minutes which could inform us that we are missing users due to memcache.

**Comment by rfk** [comment]
I fixed the graph that splits out completion ratio by context:

  https://sql.telemetry.mozilla.org/queries/1200/source#2099

The first-run contexts definitely perform worse than people who are deliberately setting up sync via preferences.

**Comment by rfk** [comment]
Here's a breakdown of time-to-signin-confirmation based on flow events:

  https://sql.telemetry.mozilla.org/queries/1227/source#2132

It clusters strongly around 1 minute, and looking at the shape of it, it doesn't seem like we could be losing 10% of the events to the time boundary on flows.

Also interestingly, the maximum reported flow_time for a sign-in confirmation event is around 3000 seconds, which is longer that I thought would be possible given how we manage this data in memcached; @philbooth can you clarify whether it makes sense for us to be getting `account.confirmed` flow events after so much time?

**Comment by rfk** [comment]
The plot thickens; over in https://github.com/mozilla/fxa-auth-server/issues/1457#issuecomment-247546013 @philbooth identifies some flows that appear to be missing the `account.confirmed` or `account.verified` event.  If we are indeed failing to properly emit these in all cases, then it could explain the differents between re:dash and kibana here.

**Comment by davismtl** [comment]
from mtg:
Finalizing conclusion and next steps.
Alex and @rfk are flagged for review.
