### ISSUE TITLE
Improve FxA UX guidelines

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#31]
Currently, FxA OAuth is being integrated with a different design across Mozilla properties and partners. 

https://marketplace.firefox.com/
https://testpilot.firefox.com/
https://getpocket.com/login

Also important to note, Persona is going away and more Mozilla sites will be turning to FxA. We want to set a standard ASAP.

We need to design standard button in different sizes to facilitate a standard integration of FxA OAuth.

**Comment by davismtl** [comment]
@ryanfeeley 
If we wanted to design buttons, who do we normally ask? Anyone assigned to FxA?
Do you currently have a process for creative content requests?

**Comment by ryanfeeley** [comment]
@davismtl I usually talk with @shorlander and assign an issue to him.

**Comment by ryanfeeley** [comment]
Also don't forget: https://addons.mozilla.org/

**Comment by shorlander** [comment]
For Mozilla properties I don't think we need anything branded. It should just say "Sign in" and take you to the FxA sign in.

We could provide some guidelines for a "Sign in with Firefox Account" button for 3rd party sites like Pocket. No guarantee they will use it however.

For example I haven't seen a lot of instances where sites are using the recommended buttons for signing in with Google/Facebook/etc.

**Comment by vladikoff** [comment]
I really wish we had a standard for the button. It's not clear to me why addons cannot put a proper login button and has to use text.

**Comment by vladikoff** [comment]
However it's up to the UX / Marketing teams.

**Comment by ryanfeeley** [comment]
One thing was made clear during Persona research. Users expicitly need to see a way to BOTH log in and register. And one should be dominant.

I agree with @shorlander in that trying to force a button style is pointless. Site owners maintain a single style for their site and don't necessarily want a differently-styled button on their site.

Unlike Google, Mozilla sites tend to vary in style a lot more.

I finally found the UX guidelines I created that allowed for more flexibility.

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/UX_Guidelines

**Comment by shorlander** [comment]
> I really wish we had a standard for the button. It's not clear to me why addons cannot put a proper login button and has to use text.

It can be a button.. I just mean that I think the button should say "Sign in" or "Log in" on Mozilla properties. The button shouldn't say "Sign in with a Firefox Account".

The problem with a standard button is that all of the sites listed so far have different button styling. So I am not sure it is an improvement to shoe-horn in a standard FxA sign-in button that might not look great.

**Comment by davismtl** [comment]
I think there should be various formats for flexibility but a recognizable button.

Pros:
-A consistent UX will make it more familiar to users. 
-It creates confidence (If you saw black or red FB login button, would you trust it?)
-It will help users better understand that they are making a Firefox Account and not an AMO or MDN account, for example.
-A recognizable button will make it more evident to users that they don't have to make a new account on every one of our websites. 
-I think it is even more important across Mozilla properties to use a standard when there is no standardization. For example, GitHub and Persona accounts logins are being used on our sites. and each of which are easily recognizable. Why would we give FXA a handicap or require the user to click on login to figure out they mean FXA?

As per the argument that site owners don't want a forced button style, this request came from one of the sites requesting our login buttons. Normally site owners don't complain about GitHub, Google and Facebook's standardized login buttons and when they deviate from recommended, they are still very recognizable. I don't think sites will complain if we create a standard or "highly recommended" set of 5 different ones that are easily recognizable by the user.

We need something recognizable and if the solution is just a style guide, than so be it but right now, we are creating likely creating unnecessary confusion by not having a standardized login button.

As an example, see here: https://www.google.com/search?q=facebook+login+button&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj9n6b4rIPOAhULzWMKHVuBBMsQ_AUICCgB
(many styles but all very recognizable)

**Comment by ryanfeeley** [comment]
Here's a list of screenshots of current and potential future FxA reliers, including the FxA Sync registration screen for reference.
![fxa-sync](https://cloud.githubusercontent.com/assets/68213/17106818/c2281304-525a-11e6-86b3-4435b29d9fab.png)
![fxa-marketplace](https://cloud.githubusercontent.com/assets/68213/17106814/c225a36c-525a-11e6-9780-0240dc4dbbdf.png)
![fxa-amo](https://cloud.githubusercontent.com/assets/68213/17106817/c2270eb4-525a-11e6-9889-f35d84c879d7.png)
![fxa-mdn](https://cloud.githubusercontent.com/assets/68213/17106813/c2248c0c-525a-11e6-8c42-bd7421f5c94c.png)
![fxa-bugzilla](https://cloud.githubusercontent.com/assets/68213/17106816/c2261f4a-525a-11e6-856c-dbe24786312a.png)
![fxa-wiki](https://cloud.githubusercontent.com/assets/68213/17106815/c225ac68-525a-11e6-8139-10cd8d696710.png)
![fxa-pocket](https://cloud.githubusercontent.com/assets/68213/17106820/c231bbde-525a-11e6-970b-9852f1b0c64f.png)

**Comment by davismtl** [comment]
Thanks Ryan! Great to see them all side by side.

**Comment by ryanfeeley** [comment]
One question I'd like solved is, if the user is already signed into the browser (with Sync), what can we do (technically) to make this part of AMO more enticing for login:
![803712495_10246074619060104258](https://cloud.githubusercontent.com/assets/68213/17416633/0564b53c-5a5d-11e6-8ad3-6647741b7906.jpg)
Any ideas @rfk @shane-tomlinson @vladikoff?

**Comment by rfk** [comment]
> if the user is already signed into the browser (with Sync), what
> can we do (technically) to make this part of AMO more enticing for login:

This is a good idea, let's spin it off to a separate feature card

**Comment by rfk** [comment]
@ryanfeeley says RESOLVED/WONTFIX for now until we have reliers for which we think it will add value

**Comment by davismtl** [comment]
@ryanfeeley Rebecca Billings had a request for buttons or style guides.
Based on product meeting, you already made style guides but said nobody used them. Please link to that guide here so I can provide it to Rebecca and to anyone who requests it in the future. 

I also think that this has to do with cognitive ease for the end user and less about imposing a design to other sites.

**Comment by ryanfeeley** [comment]
@davismtl Here they are. Very flexible. https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/UX_Guidelines
One thing we learned from Persona was that people tend to look for distinct registration and login button. We often heard "Sign in with Persona? I don't know what Persona is, I just know I don't have one, so I can't sign in with it."
We know that users will often have a Firefox Account but be unaware of it, so instead of looking like a special experience apart from the relying site, it's best to just look like their own native login system.

**Comment by davismtl** [comment]
Thanks for sharing. Great article, it certainly gives a lot of flexibility. 
I like the first part "Communicate accounts consistently" but I think this deserves to be elaborated more.

You've recently identified 11 different user states, what should those look like? You also mentioned last week that none of our products are using the same wording around FxA. What should that look like?

These lead to more questions:
What should login/registration forms look like? Is there a standard here? Should there be any mention of Firefox Accounts above a login or registration form? Should we provide screenshots as examples? 

I feel like the reasoning in the last paragraph of your comment above is a bit flawed.

If they all look native to the sites, users with existing accounts will try to make a new account but will be unable to. Seems like this problem will compound over time as more a more Firefox/Mozilla products integrate FxA. Inversely, users create their accounts for the first time outside of the browser/sync flow, we don't want them to fail login/signup when they try sync for the first time.

I think we shouldn't compare Person and FxA too much because I'm guessing that FxA is already more used than Persona ever was due to the fact that it's built-in to our browsers and automatically reaches a wider audience. Let's make sure we validate assumptions around FxA with FxA measurements and tests rather than based on Persona.

I really don't think that this issue is resolved. I will re-open it.

**Comment by ryanfeeley** [comment]
@davismtl I'm okay with it being reopened, as the guidelines could use more work, but we should probably rename the issue. "Design Standardized FxA Button" is too implementation-specific. How about "Improve FxA UX guidlines"?

**Comment by davismtl** [comment]
Agreed. That makes sense. Name changed. If we won't work on the button, we should at least make sure our guidelines our solid.

**Comment by vladikoff** [comment]
from mtg: 
- got existing guidelines on MDN
- how would people find it? direct link to it if anyone asks.
