### ISSUE TITLE
Send Notification to User when FxA is Disconnected from Device

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#33]
If a user resets his password, all devices will be disconnected. We should send their other devices push notifications when they are active to re-login with their new password.

This could also be useful in the scenario where we may disconnect and force a user to reset his password.

**Comment by vladikoff** [comment]
from mtg:
- in Nightly this already works when you go into Device manager and disconnect the device.
- Password reset should work with Train 67 to send a Push notification to the browser.
- Need to decide if we want to push notifications as actual notifications or just do things in the background
- Need to sync up with @eoger about the status of this.

**Comment by davismtl** [comment]
done
