### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-features#34]
this is edited by Alex & Ryan
![1940i](https://cloud.githubusercontent.com/assets/68213/17154464/2645ec04-534f-11e6-89ef-87d46ff3504b.jpg)
# [ Feature Title ]
## Problem Summary

> Talk about current goals of the system and how they aren't being met. What outcomes are we not delivering? This can also include an explicit request for improvement that doesn't dictate a specific or concrete solution.
### Assumptions (optional)

> This is where you talk about what you assume to be true. This could include assumptions around what users are doing, errors, gaps, etc., based on anecdotes, opinions, testing, or data.

---
## Outcomes

> What are the outcomes you want to achieve? What is the success criteria?
## Hypothesis

> A high level hypothesis of how the feature you're proposing is going help us achieve the outcomes listed above. I recommend this be a sentence of the form:
> 
> We believe that
> (doing this/building this/creating this experience)
> for (these people)
> will achieve (this outcome).
> We will know this is true when we see this
> (qualitative feedback/quantitative feedback/KPI change).
## Metrics

> How are you going to measure the outcome / success?
> 
> **Please provide sample artifact graphs here.**

---
## Detailed design

> This is the bulk of the RFC. Explain the design in enough detail for somebody familiar
> with the language to understand.
> This should get into specifics and corner-cases, and include examples of how the feature is used.
### Unresolved questions and risks (optional)

> What parts of the design are still TBD?

---

**Comment by rfk** [comment]
IIUC we're not going to take this approach, so closing this out.
