### ISSUE TITLE
Connect Firefox Mobile from signup_complete screen

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-features#35]
An apparently common flow for users signing up is to check their mobile device once they reach the "confirm your email" screen. On their second device, once clicking the link in their email, they are sent to a signup_complete screen, letting them know the original device is logged in. The metrics show that of the people who are sent to the signup_complete screen, **15% are using Firefox for Android**.

This is what they see.

![screenshot of signup_complete on fennec](https://cloud.githubusercontent.com/assets/51479/17183190/56feb07e-53db-11e6-8252-e5047a53e9a3.png)

 They are already in a Firefox browser! And we know what Account they just created! We can improve this experience and help them quickly connect this second Firefox they already have.

---

We could improve this experience in 2 steps: 1) offer a big blue "Connect this device" button, and then ask for the password again, 2) eventually no longer need to ask for the password.
1. We know the account uid, and they _just_ proved ownership of their email, by following the verify link, so we can easily generate a new sessionToken and hand it to the device. We do require the password to generate the sync keys, so at first we would need to ask them for the password again.
2. However, since we know for sure its the user, asking for the password again is just friction that we can get around. If the user's other device is still open to Firefox account, then we can facilitate connecting them directly, such as with WebRTC, or using the previous JPAKE architecture we used previously for Sync. This would allow us to securely send over the Sync keys to the second device without ever giving them to us, and we can eliminate the need to even enter a password on the second device.

The end result would be: big button "Connect this device?" Tap button. "Awesome! user@example.domain, welcome to Sync!".

/cc @davismtl

**Comment by davismtl** [comment]
Great idea! I love how you propose it in phases too. Makes things easier that way.

To expand on the phase 2 of your idea (require no password), I would like to perhaps propose a phase 3. If a user opens the link on the phone and Chrome loads, could the download button for Firefox "deeplink" so that once they finish installing Fx, their account is already setup? We could pass a short lived token as a UTM parameter to our mobile ad tracking tools (Adjust) and retrieve it once the app is opened. (there might be a better way but makes for a prototype idea)

**Comment by rfk** [comment]
> could the download button for Firefox "deeplink" so that once they finish installing Fx,
> their account is already setup? 

FWIW, I would love love love to get to this point of seamlessness in the experience, so I'm pretty hopeful that the phased approach here would let us work towards it.

**Comment by vladikoff** [comment]
from mtg:
- not sure if metrics is correct, we might have the 15% be part of those who setup sync, not those who verify on that device.
- need to check the "Sync Preferences" flow here. Not sure if it only is for about:accounts
- need to check if the marketing /sync  page , see if that works on Android.

**Comment by shane-tomlinson** [comment]
We have this now! It was built in [connect another device phase 1](https://github.com/mozilla/fxa/tree/master/features/FxA-51-connect-another-device).
