### ISSUE TITLE
Integrate FxA OAuth with [Confidential]

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#36]
This topic is confidential. Don't leave any comments here. There is apparently no private bug open either on this topic.

Just heard that an idea floating around for months is actually happening: https://docs.google.com/document/d/17WcPFizPoi9K9hdgCvtDSamPeM9gqUF24ZaMawg79ng/edit#heading=h.jjo9sxtc2y91

**Comment by davismtl** [comment]
Just a little note. I had a couple of meetings around this yesterday. I expressed our concerns and explained our current priorities and how they will impact this proposed project. Apparently no timeline is currently set so they will reach out to engineering managers, project manager and product managers when they try to define one.

**Comment by rfk** [comment]
@davismtl this project died right, we can safely close this out?

**Comment by davismtl** [comment]
I am pretty sure it did.
closing
