### ISSUE TITLE
Increase Visibility of CTA to download mobile in Preferences

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#38]
If a user only has one device connected to Sync and his account, greatly increase the visibility of the CTA to download Firefox for Android and iOS.

We recommend using the native buttons of the app stores for easy recognition on behalf of the users.

**Comment by davismtl** [comment]
![preferences](https://cloud.githubusercontent.com/assets/19537086/17782931/90fb4b1a-652a-11e6-91c5-746c523f5ca1.png)

**Comment by shane-tomlinson** [comment]
This is in-browser content and will need to be fixed there.

cc @mhammond

**Comment by davismtl** [comment]
ok thanks. I'll add this to Sync product board.

**Comment by davismtl** [comment]
https://trello.com/c/BkDJfqvs/46-improve-mobile-cta-in-sync-preferences
