### ISSUE TITLE
iOS: Change default message from Sign in to Register

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#40]
On iOS, by default, we ask users to sign in rather than register. I would like us to test both to understand the impact on sign in and registration.

The current situation results in 3x more sign ins than registrations.

**Comment by vbudhram** [comment]
Is there a way to do this on the FxA side @vladikoff , possibly through an experiment of sorts? FxiOS explicitly opens the [sign-in](https://github.com/mozilla/firefox-ios/blob/master/Account/FirefoxAccountConfiguration.swift#L95) page.

**Comment by shane-tomlinson** [comment]
@davismtl, @vbudhram - I would rather _not_ override the explicit decisions made by the iOS developers. If the opener requests the /signin page, they should get the /signin page, otherwise we are going to end up in some state table hell. The iOS client should request the /signup page instead.

**Comment by davismtl** [comment]
Thanks Shane. That makes sense.

Is there any way for us to A/B test this beforehand?
This way we would not request a change without being certain that it is for the best.
