### ISSUE TITLE
Remove "alternately" text links from our emails

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#43]
@ryanfeeley has raised concerns that they're confusing, particularly in security-related emails where users might think "alternately" means "if you dont want to allow this action, click here".  Let's try removing them and seeing if it affects our core metrics.

I'm filing this as a feature, because it seems ripe for doing as an experiment, and would need measuring and review in the product meeting.

**Comment by rfk** [comment]
There's metrics on how often folks use the "alternately" link available here: https://app.datadoghq.com/dash/172590/fxa-content---emails

**Comment by shane-tomlinson** [comment]
> There's metrics on how often folks use the "alternately" link available here: 

I find it most useful to zoom out the time span displayed. When looking at "last hour" only, because of sampling, there are so few requests per minute that any use of the alternatively link shows a huge spike.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Yeah, I try to go as far back as possible. I wish datadog could take in ranges larger than a month without choking. Basically it looks like over the past month 1.6% of verifying users are clicking the text link, and 3.2% of confirming users are the clicking the text link. Too big of a discepancy. Certainly not acceptable if it's true if half of 3.2% of our users are inadvertently giving access to an unknown device.

**Comment by mhammond** [comment]
I also note that there's no advice in the mail on what action they should take of they do not wish to confirm the signin. There _is_ text "If you suspect that someone is trying to gain access to your account, please change your password." but (a) that's under the "alternatively" text and (b) it's not clear that a user, upon receiving the email unexpectedly, would immediately conclude someone is trying to gain access to their account.

IOW, given the wording of the email, I wouldn't be surprised that a user who might expect advice on what to do if they do not authorize the signin might assume the "alternatively" link is exactly that advice.

**Comment by rfk** [comment]
>  (a) that's under the "alternatively" text 

And the alternately text is pretty big, so they're not exactly likely to scroll down past it

**Comment by shane-tomlinson** [comment]
> IOW, given the wording of the email, I wouldn't be surprised that a user who might expect advice on what to do if they do not authorize the signin might assume the "alternatively" link is exactly that advice.

As part of signin unblock, @ryanfeeley, @seanmonstar and I are working on a `Not you? Report this to us` link that I'd like to generalize.

**Comment by shane-tomlinson** [comment]
The "alternately" text has been removed from all of the emails, should this be closed?

https://github.com/mozilla/fxa-auth-mailer/pull/229

**Comment by rfk** [comment]
Actually I take that back, let's put this in measuring, and see if it has resulted in a change to the number of users clicking through the primary action versus the rest.

**Comment by rfk** [comment]
@ryanfeeley what datadog graph were you looking at that made you notice this in the first place?  Let's check back in on it.

**Comment by rfk** [comment]
Questions to resolve:
* What train did this ship on?
* Did it result in an increase in click-through of reset-password?

@rfk to find these things out

**Comment by ryanfeeley** [comment]
![screenshot 2016-12-01 17 08 53](https://cloud.githubusercontent.com/assets/68213/20838474/c88bf9d6-b876-11e6-89c6-54ead41e2e4d.png)

**Comment by rfk** [comment]
We did a bit of data diving but couldn't put together a compelling story about what happened; @davismtl do you want to dig into this more or just close it out?

**Comment by davismtl** [comment]
If there is no change is "confirm" clicks, do we see more clicks on "this wasn't me" which could result in password resets? Seems like we didn't answer that here.

Off topic, in @ryanfeeley chart, we see a big bump in sign ins at beginning of October. Remind me, what was that caused by?

**Comment by rfk** [comment]
On further digging, this shipped in late October in train-72, and here's the corresponding percentage graph from datadog:

![screen shot 2016-12-20 at 18 48 34](https://cloud.githubusercontent.com/assets/34695/21342236/0e1d928a-c6e5-11e6-8c27-2f232efedb2b.png)

The raw numbers appear to tell a similar story, with the majority of the clicks moving from "alternately" to the main CTA button.

There may be a *small* increase in the rate of password resets from the sign-in confirmation email, which corresponds to "this wasn't me":

![screen shot 2016-12-20 at 18 53 25](https://cloud.githubusercontent.com/assets/34695/21342371/b0a7ae5a-c6e5-11e6-9bde-daa11c74d22d.png)

But it's not very significant a jump.

**Comment by davismtl** [comment]
Thanks for the great analysis. This seems to be a win overall.
