### ISSUE TITLE
Add a password hint field in registration flow to minimize password resets

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#44]
Currently 6-7% of logins result in a password reset. A majority of these users only have a single device and risk losing their data. 

To avoid this, we could offer users the option of setting up a password hint.

In order to minimize sharing this hint with a malicious user, we could send the hint by email to users if they request it but there may be better ways.

I also propose that we prevent people from putting their password as the hint .
They should also be encrypted to  try to minimize stuff like this: http://zed0.co.uk/crossword/

**Comment by seanmonstar** [comment]
The scary side is that this improves the ability of an attacker who has gained access to your email account to try to gain access to all your synced passwords. Current state of affairs is that an attacker with your account can **reset** your password, which will not give them your passwords.

**Comment by davismtl** [comment]
What I am aiming for is a reduction of password resets. Why? Because a majority of users only have one device and therefore they likely lose all their sync data as a result.

Emailing the hint was a suggestion to avoid displaying it within the page where a malicious user could see it but there are perhaps other methods. 

It is worth mentioning that if a user has a compromised email, the hacker can likely gain access to a majority of the user's accounts without relying on FxA. They simply need to do password resets everywhere. Through the email, they also know everywhere the user has an account.

**Comment by seanmonstar** [comment]
That is all true. I just felt it worth including any possible security concerns along with the feature card.

**Comment by rfk** [comment]
Good writeup of some of the challenges when doing password hints, for future reference: https://www.troyhunt.com/adobe-credentials-and-serious/

**Comment by davismtl** [comment]
You're totally right Sean to bring up all these concerns and I encourage you to highlight any other ones that come to mind. I think we need to cover all of them so we are sure to address them if we ever decide to move forward with this feature.

**Comment by davismtl** [comment]
closing this
