### ISSUE TITLE
Include sync in our activity metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#46]
We care deeply about whether our users are syncing successfully, but our metrics pipeline stops at the FxA -> Sync boundary.  What if it didn't have to?  What if we could emit a "sync.succeeded" activity event every time a user synced successfully, and have that appear in re:dash alongside all our other user-related events?

It could be a bit fiddly, but we do control the servers in both systems, and we can tunnel data between them.  We could have the sync servers emit these events, have heka aggregate them into s3, and have them picked up by our redshift ingestion code just like our existing activity events.

**Comment by davismtl** [comment]
I think we are addressing this in the context of a bigger picture. we also have the ability to add sync to amplitude which we decided not to do after 2 days of data
