### ISSUE TITLE
Devices View - Phase 2

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#49]
[add feature doc link here]

**Comment by davismtl** [comment]
from mtg:
- need to double check if all phase 2 things are feasible (vlad to sync up with Ryan and Ryan)
- new styles and icons are already shipped

**Comment by davismtl** [comment]
from mtg:
- reviewing scope of phase 2 to make sure it is all feasible.
- @vladikoff any other updates here?

**Comment by vladikoff** [comment]
created PR here to update phases: https://github.com/mozilla/fxa/pull/206

**Comment by davismtl** [comment]
from mtg: 
- moving some of phase 1-2 features that are more complicated into phase 3
- phase 3 should go back into pipeline
- @rfk  and @vladikoff  to send me the features that were cut so I can formulate scope of phase 3

**Comment by rfk** [comment]
> moving some of phase 1-2 features that are more complicated into phase 3

This descoping was done, improvements shipping in train-75.

**Comment by davismtl** [comment]
from mtg:
- vlad to add results to feature doc (includes apps too)
- went out in train 75
- moving to measuring
- phase 3 document here: https://github.com/mozilla/fxa/blob/master/features/FxA-89-devices-view/README.md#phase-3

**Comment by davismtl** [comment]
@davismtl and @ryanfeeley should review what is still relevant from the quality issues listed here: https://waffle.io/mozilla/fxa?milestone=FxA-89:%20devices%20view

**Comment by davismtl** [comment]
from mtg: 
- @ryanfeeley and @davismtl have not done homework
- Will do this week!

**Comment by davismtl** [comment]
from mtg:
- still need to revisit state of affairs of device view and what would be included in phase 3
- this status update would more easily allow to prioritize
- do we want to do last sync'd date? Probably yes since it will be used by lifecycle marketing.

**Comment by rfk** [comment]
@davismtl @vladikoff will do a pass over metrics and status here tomorrow since they're in the same office.

**Comment by davismtl** [comment]
from discussions with Vlad:

from phase 2:
When viewing device view:
- 34% of users have 3 or more devices in list
- 27% of users have 2 items
- 35% of users have 1 item
- 4% have 0 items

Remaining items (taken from https://github.com/mozilla/fxa/blob/master/features/FxA-89-devices-view/README.md#phase-3): 

for phase 3 
- last active date

important to-do but related to mobile team :
- disconnect is not instant on mobile for current or remote devices. It takes up to 5 hours
- Firefox 7 for iOS will land push soon so iOS team will need to handle push to disconnect the device

for much later phase:
- connect... : button to connect a non-connected Firefox that went directly to accounts.firefox.com . Based off of phase 2 numbers, there are likely less than 4% of users in this scenario.

**Comment by vladikoff** [comment]
* Updated Device Disconnect reason breakdown:
  * ~3% - lost
  * ~3% - suspicious
  * ~34% - old
  * ~20% - would rather not say
  * ~40% - duplicated device

**Comment by davismtl** [comment]
Flags to investigate:
- I had a device with no name
- I have 2x Firefox Beta for iOS in my list
- The Beta symbol is not a recognized character
- I have duplicate Android with no name but I haven't  opened my Android device in a while so it might not have had the chance to refresh

Also, I have  in my list these 3 devices that should be the same:
 - Firefox iOS 5.3, iOS 10.1, 
 - Firefox iOS 6 , iOS 10.1
 - Firefox on Friday

Are we creating new records when app is updated rather than update existing?

Observation, when disconnecting:
- If I didn't recognize the device or remember what it was... I was tempted to mark it as suspicious even if it was prob me.
- When I disconnected a device with no name, I put 'would rather not say'
- Soo.. our options are not always perfect..
