### ISSUE TITLE
FxA-99: signin geo info

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#5]
Engineering bug tree: https://waffle.io/mozilla/fxa?milestone=FxA-99:%20signin%20geo%20info

**Comment by vbudhram** [comment]
@rfk Created a kibana graph that gives a decent breakdown of our geo location accuracy. At a high level ooks like roughly 15% of the lookups have a resolution of greater than 200km.

https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/FxA%20GeoDB%20Stats

**Comment by rfk** [comment]
Thanks @vbudhram, good to see it's at least reporting the expected level of accuracy.

To help us drive this feature to "done", here are the relevant criteria we set for ourselves in the feature doc:

  https://github.com/mozilla/fxa/tree/master/features/proposed/FxA-99-improved-login-notification#hypothesis

In addition to the above graph, we'll need to:
- Verify that all the acceptance criteria were met
- Produce the "clicks/sends" graph and see if we can observe any change in it

**Comment by vbudhram** [comment]
from mtg: Gather metrics and update feature card

**Comment by vbudhram** [comment]
Close out feature: https://github.com/mozilla/fxa/pull/185

**Comment by rfk** [comment]
Calling this one done 🎆
