### ISSUE TITLE
Improve End-to-end testing

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-features#50]
## Phase 1
- Automated testing every day with Firefox Nightly Release
- A single test that logs into sync and verifies that it is working
- Test that lists the registered device
## Phase 2
- Add OAuth client testing 
- Sync'd tabs testing

https://github.com/mozilla/fxa/issues/104

**Comment by davismtl** [comment]
from mtg:
- vlad is writing a feature doc and working with QA

**Comment by karlht** [comment]
I'm happy to be working with Vlad on this.  I may also rope in some Marionette experts from my team.

**Comment by davismtl** [comment]
from mtg:
- @vladikoff any update?

**Comment by vladikoff** [comment]
Working on a feature doc ....

**Comment by vladikoff** [comment]
Feature doc: https://github.com/mozilla/fxa/pull/207

**Comment by rfk** [comment]
Plan to do some demos at All Hands and be shipping phase 1 the week after.

**Comment by rfk** [comment]
Phase one is ready to ship after some successful demos

**Comment by davismtl** [comment]
from mtg:
- vlad is finishing this up by EOY

**Comment by davismtl** [comment]
from mtg: 
- moving to measuring

**Comment by vladikoff** [comment]
Tests running here: https://circleci.com/gh/mozilla-services/fxa-testing-e2e

**Comment by davismtl** [comment]
from mtg: 
- will be in mtv next week and will look over this with jrgm

**Comment by vladikoff** [comment]
from mtg with @jrgm :

let's update these tests to include:
* avatar / display name testing
* 5 oauth reliers
* basket subscription button in settings

**Comment by vladikoff** [comment]
allow for current stable, instead of nightly to test things in...

**Comment by vladikoff** [comment]
fix up the virtualenv for local run

**Comment by davismtl** [comment]
from mtg:
- got good feedback from jrgm last week
- still in building

**Comment by davismtl** [comment]
from mtg:
- got demo on monday
- our success criteria is that jrgm will be happy to use this
- @vladikoff can you give an update here?
- do we have a clear success criteria?
- do you want to break this card into just phase 1 and make a separate phase 2 card?
- Let's avoid having this card remain open indefinitely (not that this is the case yet)

**Comment by davismtl** [comment]
from mtg:
- Add display name test
- Can then close this out.
- Will talk with dev ops in MTV during work week to see how they like it

**Comment by vladikoff** [comment]
Display name test issue: https://github.com/mozilla-services/fxa-testing-e2e/issues/12
