### ISSUE TITLE
Mobile Push Pt3: deeplink with email

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#54]
As a phase 3 of improving the email confirmation flow to drive multi-device adoption, we would like to deep link our users to the login form with their email pre-populated. Only download links from SMS will do this.

(edit 2017-03-29)
Feature doc is located here: 
https://docs.google.com/document/d/1ObM7gZn0zt1NL4-3enBugZjJrxoD0ODthmuoaoEe7c0/edit#

**Comment by rfk** [comment]
It's now possible to pre-fill the email address on the login form in iOS, which is \o/

**Comment by davismtl** [comment]
@rfk did we already manage to do this?

My thoughts: feature doc will be short if this is already done. We will just use it to determine how we will measure the impact of the feature and log results.

**Comment by rfk** [comment]
No, we've more work to do to ship an end-to-end flow here, but @vbudhram successfully landed the required code in iOS to allow us to pre-fill the email address.

**Comment by davismtl** [comment]
@rfk @shane-tomlinson  did we want to make the email pre-population to be its own phase (via this feature card) or should it be included in phase 2? I realize I added it to the feature document of phase 2 but I could easily remove it.

**Comment by rfk** [comment]
In the spirit of shipping smaller changes and measuring/iterating more quickly, I vote for making it its own small phase and having the initial version just send you a generic link.

**Comment by shane-tomlinson** [comment]
> In the spirit of shipping smaller changes and measuring/iterating more quickly, I vote for making it its own small phase and having the initial version just send you a generic link.

I'm on board with this.

**Comment by davismtl** [comment]
OK, I'll split those up.

**Comment by vbudhram** [comment]
@davismtl Will the feature card will include prefilling for both iOS and Android? Not 100% sure of the updates needed for Android.

**Comment by davismtl** [comment]
@vbudhram great question. I don't mind splitting them up however I wonder if iOS app has enough downloads during first run fxa sign up to quickly draw conclusions and to determine if it's worth moving forward with next steps (Android and auto-login).

For now, let's start with iOS integration since we know how to do it but once we have some early numbers on SMS adoption from phase 2 (and clicks by OS), we can revisit adding Android if we think we are low on traffic.

**Comment by vbudhram** [comment]
@davismtl That sounds good to me!

**Comment by davismtl** [comment]
WIP feature document here. Forked from phase 2:
https://docs.google.com/document/d/1ObM7gZn0zt1NL4-3enBugZjJrxoD0ODthmuoaoEe7c0/edit#

**Comment by davismtl** [comment]
from mtg:
- from ryan, need to break down the engineering part by platform
- from alex: need to keep updating the feature doc
- discussed security jbuck and we're already adjust about some security questions. Need to do the same for Bit.ly
- prob need pii review for this. Julie to get this kicked off.

**Comment by davismtl** [comment]
I've updated the feature document quite a bit.
https://docs.google.com/document/d/1ObM7gZn0zt1NL4-3enBugZjJrxoD0ODthmuoaoEe7c0/edit#

@ryanfeeley , I need your help to add screenshots and complete the flows. I've left you a few comments.
@philbooth , I need your help to start the hypothetical implementation plan.
@ both of you, Feel free to add things to the acceptance criteria if I've forgotten anything.

**Comment by davismtl** [comment]
from mtg:
- we need to quickly get results from phase 2 to estimate impact of this feature phase (and that of phase 2) and to measure our OKRs.

**Comment by rfk** [comment]
From mtg:
* We need to resolve timelines for landing the client-side deeplink support in Android and iOS
  * Patches just about ready, mabye we can try to uplift?

**Comment by davismtl** [comment]
from mtg:
- @davismtl double check bug to see if there are any additional parameters that we wanted to pass in deeplink
- need to check with @grigoryk if deeplinking can be uplifted on Android.

**Comment by davismtl** [comment]
FEATURE CARD MOVED TO NEW PRODUCT BOARD. ADD NEW COMMENTS HERE: 
https://projects.growthhackers.com/s2/lcAFVS17U6pm8WO7sxE9vw
