### ISSUE TITLE
FxA-105: ip blocklist

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#6]

**Comment by rfk** [comment]
Status: successfully prototyped, need to work through some operational details of keeping the list up to date.  Blocked on actually getting the list.

Things we need to figure out before building:
- UX: nil
- Metrics: false-negative and false-positive rate

Next step is to call these out in the feature, then move to building \o/

**Comment by vladikoff** [comment]
from mtg:
- this is blocked on getting the list. 
- the feature doc is complete. probably no need to include the source for the list.
- let's work on getting the feature doc approved and merged.
- maybe we can move it to building or deployment

**Comment by rfk** [comment]
If it's close enough, maybe getting it to "defined" and letting it wait there will be valuable?

**Comment by vbudhram** [comment]
@rfk I believe the feature doc is accurate enough for us to move this to defined, https://github.com/mozilla/fxa/pull/156

**Comment by davismtl** [comment]
Next steps is to land it in listen only mode to see how many hits we get. Monitor metrics next.

**Comment by rfk** [comment]
On reflection, I have two main concerns with this feature right now:
- What list would we use for initial testing?
- How will we get reliable metrics on false-positives and false-negatives?

ISTM that getting good metrics is more-or-less blocked on other features in the pipeline, like email captcha to measure false negatives.  So I suggest that we:

1) Get the feature-doc to a state we're happy with, and merge it in github.
2) Land the initial PR if we're happy with it, to prevent bitrot.
3) Pause this feature while we focus on getting the other metrics-enabling features out the door.

@vbudhram I'm open to shipping an initial version if we have a list we're happy to use, but I worry that it wouldn't really teach us anything much about how to move the feature forward.

**Comment by rfk** [comment]
(I am also moving this out of "defined" while we have unanswered questions about the above)

**Comment by rfk** [comment]
It's funny how sometimes just commenting on something in github, will trigger a whole chain of follow-up thoughts.  Anyways, thinking about this:

> land it in listen only mode to see how many hits we get

And then this:

> I'm open to shipping an initial version if we have a list we're happy to use, but
> I worry that it wouldn't really teach us anything much about how to move the feature forward.

It sounds like one path forward may be to ignore false-positives and false-negatives for now, and focus just on measuring hit-rate.  If we have a handful of candidate lists, we can just deploy logic that checks incoming requests against each list and emits metrics on whether it matched or not.  If we see barely any traffic that matches against a particular list, then it doesn't really matter what its false-negative rate was, it's not going to deliver us much value.

The output of this "milestone 1" would be a graph like the following:

![20160819_113144](https://cloud.githubusercontent.com/assets/34695/17796076/4205655e-6601-11e6-84b0-25f6e3a767b2.jpg)

That we can use to inform further work on this feature.  @vbudhram is this what you had in mind for "deploy in metrics-gathering mode"?

**Comment by rfk** [comment]
Also here's a fun list of lists we could try out:  https://zeltser.com/malicious-ip-blocklists/

**Comment by vbudhram** [comment]
> ignore false-positives and false-negatives for now

I think this is a decent approach. I believe that a lot of value can be gained by just monitoring the performance of these lists against incoming traffic.

> checks incoming requests against each list and emits metrics on whether it matched or not

This seems reasonable. Since these lists can change rapidly, the more information we can compare it to the better I think. This was the basic idea behind metrics only mode. I can update feature card to better reflect this and add ability to compare multiple lists.

**Comment by rfk** [comment]
> What list would we use for initial testing?

Good candidates for an initial analysis might be the combined firehol lists "level 1" through "level4", which claim to cast increasingly wide nets at the cost of increasingly more false-positives:
- http://iplists.firehol.org/?ipset=firehol_level1
- http://iplists.firehol.org/?ipset=firehol_level2
- http://iplists.firehol.org/?ipset=firehol_level3
- http://iplists.firehol.org/?ipset=firehol_level4

They appear to be freely-available, although we'd need to do our due diligence to ensure licensing terms etc are OK.

**Comment by rfk** [comment]
@vbudhram is going to update the feature doc with the latest requirements and acceptance criteria.

Interesting additional list:

  http://iplists.firehol.org/?ipset=firehol_webserver

**Comment by davismtl** [comment]
from mtg:
ryan reviewed and gave thumbs up. Small changes to do and will be merged soon. 
Needs ops changes for most recent block list.
Once merged,  will move to measuring.

**Comment by davismtl** [comment]
The measuring part is shipping. Let's move phase 2-3 into backlog.

**Comment by davismtl** [comment]
from mtg:
- turned on and should be measuring
- need to double check that measuring is working as expected

**Comment by davismtl** [comment]
from mtg:
- vijay to check with jon on event metrics
- @vbudhram do you have any updates here?

**Comment by rfk** [comment]
We have a graph of this now:

  https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20IP%20Blocklist%20Stats

It shows a small number of hits on the most conservative blocklist.  Next step is to try shipping a second blocklist that's less conservative and see how that performs.

**Comment by davismtl** [comment]
from mtg: 
- @vbudhram will test a new list to see if we can hit more people
- we believe it would be valuable to track a hashed IP for the blocks, vijay will file an issue for this.

**Comment by davismtl** [comment]
from mtg:
- went as far as possible with puppet config which will do the automatic updates. Issue is out there for hashed IP (next). Need jbuck or jrgm to make sense of puppet skills.

**Comment by davismtl** [comment]
from mtg: 
- jbuck made a docker image for @vbudhram to update the list and copy it to S3
- @vbudhram will be working on this over the next week

**Comment by davismtl** [comment]
from mtg:
- jbuck made the pr and vijay made the puppet
- assuming that it gets approved, we should be good to go

**Comment by rfk** [comment]
> assuming that it gets approved, we should be good to go

It got merged \o/

Also we have hashed IPs in the kibana dashboard now:
* https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20IP%20Blocklist%20Stats

**Comment by davismtl** [comment]
- updates shipped
- numbers showing up in dashboard
- some of hits on web server are from amazon (team city)
- next steps: need to see what is coming out in the results. can we filter out team city?

**Comment by rfk** [comment]
The second blocklist is now showing up in the dashboard here: https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20IP%20Blocklist%20Stats

**Comment by davismtl** [comment]
from mtg:
- @vbudhram spoke to jrgm and the IPs being blocked seem plausible enough to be suspicious so we will move forward and block them.
- The second list picks up IPs from team city which actually catches some of our own services.
- Ryan: we don't have a feedback loop to see if we are doing it wrong. 
- If we send an unblock code, can we re-white list the IPs? (no)
- Webserver list is a bust for now but the first list is a go.
- @vbudhram to log results in feature doc and send it out to the team

**Comment by davismtl** [comment]
from mtg:
- according to @rfk final blocking goes out in train 81 so we will only have final numbers then
- we should close out this card only once we get the final numbers from train 81

**Comment by davismtl** [comment]
from mtg:
- blocking 0.0002% of requests
- blocked by firehol list
- we don't have a strategy yet for other lists which have too many false positives.
- next step: @vbudhram to write conclusion in feature document

**Comment by davismtl** [comment]
from mtg:
- no update for now
- @vbudhram will get to it soon :)

**Comment by davismtl** [comment]
from mtg:
- @vbudhram tagged us for review of results in feature document
- level 1 is in blocking mode. not web server list though (0.55% blocked). 
- do we want to move forward with a phase 2? To decide while reviewing results in feature doc

**Comment by davismtl** [comment]
from mtg:
- we're going to shelve the next steps for now.
- going to close this feature card
