### ISSUE TITLE
iOS login flow

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-features#61]
Created this card because we should probably track fixing iOS login at a higher level.
We likely need to do a UX review too.

**Comment by davismtl** [comment]
from mtg:
- @ryanfeeley needs to review user flow and make a proposal or sign-off on current proposal
- he will likely plan a Sync Fest
- Sign-in success rate by OS: https://sql.telemetry.mozilla.org/queries/2255#4122

**Comment by vladikoff** [comment]
from mtg: need to coordinate deployment and app release...

**Comment by davismtl** [comment]
from mtg:
- Going out in train-80 (early next week)
- Firefox 6.1 passed review and is ready to go

**Comment by rfk** [comment]
All the fixes have shipped, but we haven't seen any corresponding increase in sign-in success on iOS.  We need to dig into the detailed metrics here and try to figure out if it's a lingering client problem, or a problem with the metrics.

**Comment by davismtl** [comment]
from mtg:
- shipped but measuring has a bug
- will fix metrics before closing this to declare if it was a success.

**Comment by rfk** [comment]
Looks like there may be a bug in our metrics pipeline that means we can't measure this properly :-(

https://bugzilla.mozilla.org/show_bug.cgi?id=1341966

**Comment by davismtl** [comment]
Metrics are looking good now. The iOS patch has brought login success above that of Android: https://sql.telemetry.mozilla.org/queries/2255?p_start_date=2017-01-01#4122

**Comment by davismtl** [comment]
from mtg:
- we fixed our metric bug and the ios login success rate went up
- with the patch landing to UX, we increased signin success rate by approx 20%
- Volume of successful logins though nearly increased by 100% which conflicts with 20% improvement. 
- We need to follow up on this discrepancy before we close up this feature card

**Comment by davismtl** [comment]
from mtg:
- we have not investigated the discrepency
- @davismtl to investigate for next week

**Comment by davismtl** [comment]
from mtg:
- @davismtl to look into it
- phil re-imported data and q1 data should be there now

**Comment by davismtl** [comment]
Now that data has been re-imported, I don't observe the same discrepancies. I'm rerunning the query going back further to see if there is anything else to notice but so far so good:
https://sql.telemetry.mozilla.org/queries/2255?p_start_date=2017-01-01#4122

I think we can close this during product meeting.
