### ISSUE TITLE
FxA-49: CDN

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#7]

**Comment by rfk** [comment]
It's shipped!  Next step is to gather the metrics and summarize success (or otherwise) into the feature doc.

**Comment by rfk** [comment]
@shane-tomlinson  please summarize the results of this feature into https://github.com/mozilla/fxa/tree/master/features/FxA-49-cdn

**Comment by vladikoff** [comment]
from mtg: needs metrics to close this out

**Comment by davismtl** [comment]
from mtg: shane is working on it. We are re-bringing this up at every standup. ;)
