### ISSUE TITLE
FxA-89: devices view

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#8]

**Comment by rfk** [comment]
Feature document from when we were building this feature: https://github.com/mozilla/fxa/blob/master/features/FxA-16-devices-view/README.md

**Comment by rfk** [comment]
Related engineering bugs: https://waffle.io/mozilla/fxa?milestone=FxA-89:%20devices%20view

**Comment by davismtl** [comment]
@ryanfeeley shall we move the feature document back to a Google Doc while we expand on it? It might be easier to get feedback and make iterations. 

Also, are you aware of the primary changes that need to be made to the feature document? For example:
- what is good with it now?
- what is missing?
- what needs to be elaborated more?
  etc...

In any case, we should probably invite everyone to comment on the Google Doc and provide feedback.

Let me know your thoughts.

**Comment by rfk** [comment]
>  shall we move the feature document back to a Google Doc while we expand on it?

FWIW, yes, I think you should do this and link the doc here for context :-)

**Comment by davismtl** [comment]
I have created a copy of the document here: https://docs.google.com/document/d/1VrysJ4LFPZ20IeMMmRts5l_2GUHhm890rlQhD012U_g/edit# 

I will clean it up to align it more with our latest document format.

**Comment by davismtl** [comment]
@vladikoff 
I know this is in development and is still waiting for the feature document but I was wondering if it is normal that I don't see my mobile devices yet when I visit: 
https://accounts.firefox.com/settings/devices?forceDeviceList=1

Normally, I should see 2 iOS devices:
<img width="536" alt="screen shot 2016-08-05 at 5 05 54 pm" src="https://cloud.githubusercontent.com/assets/19537086/17453338/69c05914-5b2f-11e6-86f5-cf8cf5052713.png">

**Comment by davismtl** [comment]
I'm guessing that this is related to my last comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1250783

**Comment by vladikoff** [comment]
@davismtl device registration has not landed in mobile clients. Yeap https://bugzilla.mozilla.org/show_bug.cgi?id=1250783 looks like the one for iOS. 

I think there is also a bug for Android 👍

**Comment by davismtl** [comment]
@vladikoff @rfk @ryanfeeley 
I left a lot of comments on this document. 
https://docs.google.com/document/d/1VrysJ4LFPZ20IeMMmRts5l_2GUHhm890rlQhD012U_g/edit#

I think the piece that needs the most attention from you is the behavior around trying to disconnect a device (i.e. simple overlay to confirm to avoid mistakes, an email confirmation to block malicious intent, and/or capture signal via reason for disconnect, etc.). 

Thanks in advance for looking into that.

**Comment by davismtl** [comment]
Thanks @rfk for all the feedback. I've updated the document to reflect it.

I think we have a good flow now to capture signals, make sure that no device is accidentally removed, that will also allow us to educate users on next steps and to notify users of any removed devices.

I've also added a section to log results towards the bottom with definitions and a section to log our conclusion and next steps.

I am talking to @ryanfeeley tomorrow and will review the comments I left for him.

**Comment by vladikoff** [comment]
from mtg:
- feature doc in the works.

**Comment by davismtl** [comment]
Latest update from yesterday, @ryanfeeley is just finalizing the copy of the new flow around removing devices. The rest of the document is solid. We should move to defined tomorrow if all goes well.

**Comment by rfk** [comment]
This is ready to go, assigning to myself to transfer to github

**Comment by rfk** [comment]
We have a couple of outstanding questions in the github PR for this

**Comment by davismtl** [comment]
from mtg:
Phase 1 will be shipping on the 3rd of October.
Yay!

**Comment by vladikoff** [comment]
Meanwhile connected apps:  https://github.com/mozilla/fxa-content-server/issues/4213

**Comment by davismtl** [comment]
from mtg:
@ryanfeeley and alex to review services section
feeley also working on icons for devices and services

Phase 1 activating on october 3rd without apps.

**Comment by davismtl** [comment]
Phase 1 is shipping today.
Phase 2 in the work. Icons + Get app etc...
Will carry over into next sprint. Vlad is out next week.

**Comment by davismtl** [comment]
from mtg:
-splitting this card
-will move this to measuring for phase 1 (in staged rollout)
-can measure engagement ration, what reasons people disconnected, etc.
-will put a new card in building for phase 2

**Comment by vladikoff** [comment]
for the meeting: 

We got some results here: https://github.com/mozilla/fxa/tree/master/features/FxA-89-devices-view#results we can chat about those in the next product meeting and move this card out of `measuring`.

**Comment by davismtl** [comment]
from mtg:
- rolled out at 60%
- Results: https://github.com/mozilla/fxa/tree/master/features/FxA-89-devices-view#results
- 6% disconnecting suspicious devices is a baseline

**Comment by davismtl** [comment]
going to roll-out at 100%
