### ISSUE TITLE
FxA-107: ip profiling

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-features#9]
Feature doc
https://github.com/mozilla/fxa/blob/rfk/security-event-history/features/FxA-107-security-event-history/README.md

**Comment by seanmonstar** [comment]
feature document: https://github.com/mozilla/fxa/pull/176

**Comment by rfk** [comment]
This is on @rfk to review the above feature doc

**Comment by davismtl** [comment]
from mtg:
@seanmonstar needs to update designs based on comments

**Comment by davismtl** [comment]
Update, this seems to be the feature doc now: https://github.com/mozilla/fxa/blob/rfk/security-event-history/features/FxA-107-security-event-history/README.md

Will add to first comment.

**Comment by davismtl** [comment]
from mtg:
- merge the feature documents so that we can create a prototype version without multiple phases
- vijay made corresponding issue to prototype
- jrgm will dump server logs to see how many people login multiple times from the same IP (for validation)

**Comment by davismtl** [comment]
from mtg:
- jbuck provided 2 days of server logs. rfk to look through to see how many people this would impact. 
- want to know how many users are logging in from an ip that they already logged in from

**Comment by rfk** [comment]
Server log analysis is happening here: https://bugzilla.mozilla.org/show_bug.cgi?id=1313275

**Comment by davismtl** [comment]
from mtg:
- @vbudhram flagged sean for review
- may ship in 74
- will not ask to confirm sign-in from an IP where user confirmed within previous 24h
- 25% of login attempts will no longer need to confirm their login based on above criteria
- need to create a feature doc for this release

**Comment by rfk** [comment]
> may ship in 74

This is indeed shipping in train-74

**Comment by davismtl** [comment]
from mtg:
-certain emails will have to go through email confirmation flow (forced email) but only impacts functional tests (but not production)

**Comment by rfk** [comment]
As of today, this feature is in production and enabled for 100% of users with a 1-day threshold.  Let's see what sort of difference it makes in practice!

**Comment by rfk** [comment]
@vbudhram shared some graphs on this feature in the demo session today.  This graph shows the decrease in send rate of sign-in confirmation emails for previously-seen IPs:

    https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/FxA%20Sign-in%20Confirmation

And we can see a corresponding increase in the sync sign-in success rate, so far up from 
53% to 58%:

  https://sql.telemetry.mozilla.org/queries/1751/source#3117

Let's keep on eye on that change to see if it holds, but it's a good start!

**Comment by rfk** [comment]
According to [1], we see around 26% of login attempts coming from an IP address seen in the past 24 hours, and 32% from an address seen in the past week.  If we were to increase the window here from a day to a week, we might be able to get the success rate up to:

  53 + ((58 - 53) * (32 / 26)) ~= 59% success.

Not sure that's worth it, but we could try it out.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1313275#c10

**Comment by davismtl** [comment]
1 week sounds reasonable to me. It also seems like a significant gain. 11.3% improvement in login success rate.

**Comment by rfk** [comment]
Putting this back in "building" with a proposal to extend to 1 week; @seanmonstar @vbudhram thoughts on the security tradeoffs there?

**Comment by seanmonstar** [comment]
1 day seemed like a reasonable trade-off, since the time period for an attack is quite low, and the impact is quite high.

Looking at the impact for a week, though, makes me pause. Not so much so that I'd die on this hill. With a week, there's a higher chance of an IP being recycled (but then you'd have to properly guess the previous owner's email and password, which is wow). It occurs to me that it would however be easier for social attacks, like if someone logged in at a school, library, or coffee shop/wifi cafe. Again, probably not something that would happen commonly, but is that worth a maybe ~1% signin improvement?

Is it worth considering if penalized for incorrect logins, such that if you had some bad login attempts at that IP, you should still do confirmation? Maybe after a couple, to allow for typos of your password?

**Comment by rfk** [comment]
Let's revisit the metrics on this and see if we can find a "sweet spot" of impact vs makes-us-nervous.

**Comment by rfk** [comment]
The metrics here: https://bugzilla.mozilla.org/show_bug.cgi?id=1313275#c9

Suggest that we pick up a few extra percent of users after 48-72 hours, and then the effect tapers off.  So perhaps we can simply double it to 48 hours and see if we can measure a corresponding increase?

**Comment by rfk** [comment]
Another random thought: if the user has multiple verified logins from the same IP, we could treat that as a stronger signal about their ownership of that IP address.  For example, 1 verified login means we trust it for 24 hours, but 2 verified logins could mean we trust it for a week.

No idea how many extra users that would pick up though :-)

**Comment by davismtl** [comment]
from mtg:
- moving back to measuring for @rfk 
- 1 week might be too much. We might be able to get most of the gains of 1 week within 48 or 72h.

**Comment by rfk** [comment]
I made a new graph based on the ip-address data being exported to re:dash:

  https://sql.telemetry.mozilla.org/queries/2034/source#3664

24 hours -> 24%
48 hours -> 27%
72 hours -> 29%
1 week -> 32%

So we can definitely get gains by increasing this even we don't go to a full week.

**Comment by davismtl** [comment]
![screen shot 2017-01-04 at 5 49 00 pm](https://cloud.githubusercontent.com/assets/19537086/21666368/1cde3e42-d2a6-11e6-9156-826375541b80.png)

Feels like 72 is the tipping point.
x = hours , y = %

**Comment by davismtl** [comment]
from mtg: 
- after discussion, our recommendation is to do 72h because it seems like the right balance of performance vs risk.
- @rfk please sign-off on this recommendation too
- Will move back into building

**Comment by rfk** [comment]
> after discussion, our recommendation is to do 72h because it seems like the right balance of performance vs risk.
> @rfk please sign-off on this recommendation too

👍

**Comment by vladikoff** [comment]
from mtg: shipping in train-79

**Comment by rfk** [comment]
from mtg: not shipped yet due to train-79 delay

**Comment by davismtl** [comment]
from mtg:
- auth server shipped
- moving this to measuring

**Comment by davismtl** [comment]
from mtg:
- somewhat we can see there is no noticeable improvement to login success rate
https://sql.telemetry.mozilla.org/queries/1751#3117
- @vbudhram to wrap up feature document with results, conclusion and next steps

**Comment by davismtl** [comment]
from mtg:
- @vbudhram logged results in Feature doc
https://github.com/mozilla/fxa/pull/226
- assigning this feature to @rfk to double check that everything is good and close up feature card.

**Comment by davismtl** [comment]
Done. closing. feature card complete.
